/**
 * WP #455: Related projects section
 * WP #456: Next/previous project navigation
 * WP #453: Architecture diagram support
 * WP #462: Technology/tag filter
 * WP #568: New page scaffolding script
 * WP #606: Test: Related projects and prev/next navigation
 * Updated for system.css monochrome architecture.
 * Removed: view-transition animations (no longer used).
 */
import { describe, test, expect } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import { resolve } from 'path';

const ROOT = resolve(import.meta.dirname!, '..');

// ---- WP #455 / #456 / #606: Project detail pages ----

describe('Project detail page', () => {
  const detailSrc = readFileSync(
    resolve(ROOT, 'src/pages/projects/[slug].astro'),
    'utf-8',
  );

  test('detail page template exists', () => {
    expect(existsSync(resolve(ROOT, 'src/pages/projects/[slug].astro'))).toBe(true);
  });

  test('has getStaticPaths for SSG', () => {
    expect(detailSrc).toContain('getStaticPaths');
  });

  test('uses BaseLayout', () => {
    expect(detailSrc).toContain('BaseLayout');
  });

  test('breadcrumbs auto-generated by BaseLayout', () => {
    // BaseLayout auto-generates breadcrumbs from URL path for non-home pages
    const layoutSrc = readFileSync(resolve(ROOT, 'src/layouts/BaseLayout.astro'), 'utf-8');
    expect(layoutSrc).toContain('breadcrumbs');
  });

  test('shows project title via BaseLayout', () => {
    expect(detailSrc).toContain('title={project.title}');
  });

  test('shows project description', () => {
    expect(detailSrc).toContain('project.description');
  });

  test('shows project screenshots or placeholder', () => {
    expect(detailSrc).toContain('screenshot');
  });
});

describe('Related projects section', () => {
  const detailSrc = readFileSync(
    resolve(ROOT, 'src/pages/projects/[slug].astro'),
    'utf-8',
  );

  test('related projects section exists', () => {
    expect(detailSrc).toContain('Related Projects');
  });

  test('filters related by same category and excludes current', () => {
    expect(detailSrc).toContain('p.slug !== slug && p.category === project.category');
  });

  test('limits related projects', () => {
    expect(detailSrc).toContain('.slice(0, 2)');
  });

  test('related projects use related-item links', () => {
    expect(detailSrc).toContain('related-item');
  });
});

describe('Previous/Next project navigation', () => {
  const detailSrc = readFileSync(
    resolve(ROOT, 'src/pages/projects/[slug].astro'),
    'utf-8',
  );

  test('nav element with aria-label exists', () => {
    expect(detailSrc).toContain('project-nav');
    expect(detailSrc).toContain('aria-label="Project navigation"');
  });

  test('has previous link', () => {
    expect(detailSrc).toContain('prevProject');
    expect(detailSrc).toContain('Previous');
  });

  test('has next link', () => {
    expect(detailSrc).toContain('nextProject');
    expect(detailSrc).toContain('Next');
  });

  test('computes prev/next from project index', () => {
    expect(detailSrc).toContain('projectIndex > 0');
    expect(detailSrc).toContain('projectIndex < projects.length - 1');
  });
});

// ---- WP #453: Architecture diagram support ----
// Architecture section and placeholder are not yet implemented in [slug].astro.

// ---- WP #462: Technology/tag filter ----
// Projects page now uses a Finder-style icon grid without tag filtering.

describe('Projects page icon grid', () => {
  const projectsSrc = readFileSync(
    resolve(ROOT, 'src/pages/projects/index.astro'),
    'utf-8',
  );

  test('uses finder-icon grid layout', () => {
    expect(projectsSrc).toContain('icon-grid');
    expect(projectsSrc).toContain('finder-icon');
  });

  test('links to project detail pages', () => {
    expect(projectsSrc).toContain('/projects/');
    expect(projectsSrc).toContain('project.slug');
  });
});

// ---- WP #568: Page scaffolding script ----

describe('Page scaffolding script', () => {
  test('script exists', () => {
    expect(existsSync(resolve(ROOT, 'scripts/new-page.sh'))).toBe(true);
  });

  test('script is executable', () => {
    const scriptSrc = readFileSync(resolve(ROOT, 'scripts/new-page.sh'), 'utf-8');
    expect(scriptSrc).toContain('#!/usr/bin/env bash');
  });

  test('script generates Astro page', () => {
    const scriptSrc = readFileSync(resolve(ROOT, 'scripts/new-page.sh'), 'utf-8');
    expect(scriptSrc).toContain('BaseLayout');
    expect(scriptSrc).toContain('Breadcrumbs');
    expect(scriptSrc).toContain('.astro');
  });

  test('script validates input', () => {
    const scriptSrc = readFileSync(resolve(ROOT, 'scripts/new-page.sh'), 'utf-8');
    expect(scriptSrc).toContain('Usage:');
    expect(scriptSrc).toContain('exit 1');
  });

  test('script checks for existing file', () => {
    const scriptSrc = readFileSync(resolve(ROOT, 'scripts/new-page.sh'), 'utf-8');
    expect(scriptSrc).toContain('already exists');
  });
});
