FROM node:20-bookworm-slim

# xelatex for PDF compilation
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      texlive-xetex texlive-fonts-extra texlive-latex-extra && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app/editor
COPY editor/package*.json ./
RUN npm ci --production
COPY . /app

EXPOSE 3000
CMD ["node", "server.js"]
