FROM python:3.12-slim

WORKDIR /app
RUN pip install --no-cache-dir \
    flask \
    torch torchvision torchaudio \
    numpy scipy pillow \
    mistune pyyaml

COPY . .

EXPOSE 5001
CMD ["python", "-m", "classifiers"]
